server:
  port: 8081

spring:
  application:
    name: ingestion-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

