server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ingestion-service
          uri: lb://ingestion-service
          predicates:
            - Path=/api/v1/ingestion/**
        - id: tracking-service-ws
          uri: lb://tracking-service
          predicates:
            - Path=/ws/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/v1/tracking/**
        - id: shipment-service
          uri: lb://shipment-service
          predicates:
            - Path=/api/v1/shipments/**
        - id: optimization-engine
          uri: lb://optimization-engine
          predicates:
            - Path=/api/v1/optimization/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/logiflow


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
